spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db6
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
#  mapper-locations: classpath:dataImpl/*/*Mapper.xml
  mapper-locations: classpath:*.xml